name: ☁️ Pull Request Runner

on:
  pull_request: {}
  workflow_dispatch: {}

env:
  PROJECT_NAME: Sequencer
  IOS_GIT_AUTHORIZATION_FOR_WORKFLOWS: ${{ secrets.IOS_GIT_AUTHORIZATION_FOR_WORKFLOWS }}
  CACHE_VERSION_LINT: formatLintCache

jobs:

#-------------------------
# Run Linting & Formatting
# (∩｀-´)⊃━☆ﾟ.*･｡ﾟ
#-------------------------

  lintAndFormat:
   runs-on: macos-14
   steps:
    - uses: actions/checkout@v4
      name: 🔄 Checking Out Repository

    - name: 🔒 Cache Swift Lint And Swift Format Dependencies
      id: cache-lintingAndFormatting
      uses: actions/cache@v4
      with:
          path: |
            ~/.mint
          key: ${{ runner.os }}-cache-lintingAndFormatting-${{ env.CACHE_VERSION_LINT }}-${{ hashFiles('**/configurationCI.sh') }}
          restore-keys: |
            ${{ runner.os }}-cache-lintingAndFormatting-${{ env.CACHE_VERSION_LINT }}-
     
    - name: 📊  Determine Swift Lint And Swift Format Dependency Status
      run: |
          if [ "${{ steps.cache-lintingAndFormatting.outputs.cache-hit }}" == "true" ]; then
            echo "✅ Linting & Formatting Cache Detected. Saving Some 🧀."
          else
            echo "🐌 Dependencies Not Cached So Installing Them."
          fi
          
    - name: 🛠️ Run Install Script
      if: steps.cache-lintingAndFormatting.outputs.cache-hit != 'true'
      run: bash fastlane/scripts/configurationCI.sh
      shell: bash

    - name: ✨ Linting & Formatting Code
      run: |
        fastlane lint_and_format_project_with_validation --verbose
        echo "🔥 Formatting & Linting Completed 🤣"
      working-directory: fastlane
